name: Semgrep SAST

on:
  push:

jobs:
  semgrep-sast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Semgrep SAST
        uses: returntocorp/semgrep-action@v1
        with:
          args: --config auto --verbose
